"""initial clean migration

Revision ID: 61b98ddb3441
Revises: 
Create Date: 2026-04-02 12:17:17.092907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b98ddb3441'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('department', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_claim', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_code'), ['code'], unique=True)

    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_tr', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ledger', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_id')
    )
    op.create_table('main_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_tr', sa.String(length=255), nullable=True),
    sa.Column('code_prefix', sa.String(length=10), nullable=False),
    sa.Column('department', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_ref_code', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('cash_debt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('paid_off', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_cash_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date_paid', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installment_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('initial_payment', sa.Float(), nullable=False),
    sa.Column('monthly_installment', sa.Float(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('paid_off', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_tr', sa.String(length=255), nullable=True),
    sa.Column('code_prefix', sa.String(length=10), nullable=False),
    sa.Column('department', sa.String(length=20), nullable=False),
    sa.Column('main_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['main_category_id'], ['main_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'coupon_id', name='uq_user_coupon')
    )
    with op.batch_alter_table('user_coupon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_coupon_coupon_id'), ['coupon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_coupon_user_id'), ['user_id'], unique=False)

    op.create_table('installment_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date_paid', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['installment_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('barcode_value', sa.String(length=60), nullable=True),
    sa.Column('barcode_image', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=20), nullable=False),
    sa.Column('serial_no', sa.String(length=40), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_tr', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_tr', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('capital_price', sa.Float(), nullable=False),
    sa.Column('base_cash_price', sa.Float(), nullable=False),
    sa.Column('sub_category_id', sa.Integer(), nullable=False),
    sa.Column('is_discounted', sa.Boolean(), nullable=True),
    sa.Column('discount_price', sa.Float(), nullable=True),
    sa.Column('discount_start', sa.DateTime(), nullable=True),
    sa.Column('discount_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('serial_no')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_tr', sa.String(length=255), nullable=True),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installment_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installment_product_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['installment_product_id'], ['installment_product.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_image_product_id'), ['product_id'], unique=False)

    op.create_table('product_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('value_tr', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('capital_price', sa.Float(), nullable=False),
    sa.Column('base_cash_price', sa.Float(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variant_product_id'), ['product_id'], unique=False)

    op.create_table('property_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('value_tr', sa.String(length=100), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('sale_type', sa.String(length=20), nullable=False),
    sa.Column('sell_price', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('manual_name', sa.String(length=200), nullable=True),
    sa.Column('manual_code', sa.String(length=60), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('offer_kind', sa.String(length=30), nullable=False),
    sa.Column('product1_id', sa.Integer(), nullable=False),
    sa.Column('product2_id', sa.Integer(), nullable=False),
    sa.Column('third_product_id', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('stock_limit', sa.Integer(), nullable=True),
    sa.Column('stock_remaining', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product1_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product2_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['third_product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_category_property',
    sa.Column('sub_category_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_category.id'], ),
    sa.PrimaryKeyConstraint('sub_category_id', 'property_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_category_property')
    op.drop_table('special_offer')
    op.drop_table('sale')
    op.drop_table('property_value')
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variant_product_id'))

    op.drop_table('product_variant')
    op.drop_table('product_property')
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_image_product_id'))

    op.drop_table('product_image')
    op.drop_table('installment_item')
    op.drop_table('property')
    op.drop_table('product')
    op.drop_table('installment_payment')
    with op.batch_alter_table('user_coupon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_coupon_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_coupon_coupon_id'))

    op.drop_table('user_coupon')
    op.drop_table('sub_category')
    op.drop_table('installment_product')
    op.drop_table('general_cash_payment')
    op.drop_table('cash_debt')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('main_category')
    op.drop_table('customer')
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_code'))

    op.drop_table('coupon')
    op.drop_table('brand')
    # ### end Alembic commands ###
